# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3d609782bf24c48e26b5dfdcc61bdcd00b38cadc78ac68b4f8c8ea3d108e4ad8e5251df0729b71f50182aa8221a746e92d7c4d9719f39e1777d33df5cc785103

test:
  secret_key_base: c20912593b6a17f4ada3a69643a6dcb826fb1945636ee99ad5ed3adf8eed159d44e9652343c356430349444233336f1c0a91ab61d6781185725bbe27733b1688

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
